server:
  port: 8080
spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://127.0.0.1:8081
management:
  endpoints:
    web:
      exposure:
        include: ["health","info"]
  health:
    how-details: ALWAYS


